# Site settings
title: "OnClick Blog"
email: 
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: "/onclick" # the subpath of your site, e.g. /blog/
url: "http://ctacon.me" # the base hostname & protocol for your site
twitter_username: carlosjtacon
github_username: carlosjtacon
permalink: "/:year/:title/"

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]